name: Test Homebrew formula

on:
  pull_request:

jobs:
  test:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Build Homebrew formula
        run: brew install ./Formula/riff.rb
      - name: Test Homebrew formula
        run: brew test ./Formula/riff.rb
